# config/config_model.yaml

MODEL_NAME: "Outage_Predictor_GBM"

XGBOOST_PARAMS:
  objective: 'binary:logistic'
  n_estimators: 150
  learning_rate: 0.1
  max_depth: 5
  random_state: 42
  eval_metric: 'logloss'